# Требования для повышения лорда Beast Lord The New Land
# Основано на пользовательской таблице требований

# Требования по уровням лорда
lord_requirements:
  10:
    buildings:
      улей: 4
      ферма_грунта: 4
      ферма_яблок: 4
      ферма_листьев: 4
      пруд: 4
      флора_эволюции: 7
      склад_песка: 7
      склад_листьев: 7
      склад_грунта: 7
      склад_яблок: 7
      склад_воды: 7
      голово_всеядных: 10
      логово_плотоядных: 10
    research:
      развитие_территории: 1
      изобилие_света: 5
      сапротрофное_удобрение: 5
      выхлый_грунт: 5
      плодородная_почва: 5
      журчащий_источник: 5
      массивный_песчаник: 5
      гигантский_улей: 10
      загруженный_сборщик: 5
      резвый_подъем: 10
      мягкая_почва: 10
      скоростная_перевозка: 10
      меткая_резка: 1

  11:
    buildings:
      улей: 11  # 1шт до 11
      ферма_грунта: 11  # 1шт до 11
      ферма_яблок: 11  # 1шт до 11
      склад_песка: 8
      склад_листьев: 8
      склад_грунта: 8
      склад_яблок: 8
      флора_эволюции: 8
      голово_всеядных: 11
      логово_плотоядных: 11
      жилище_детенышей: 11  # 4шт до 11
      центр_альянса: 11
    research:
      накопитель: 10

  12:
    buildings:
      улей: 12  # 1шт до 12
      ферма_грунта: 12  # 1шт до 12
      ферма_яблок: 12  # 1шт до 12
      склад_песка: 9
      склад_листьев: 9
      склад_грунта: 9
      склад_яблок: 9
      флора_эволюции: 9
      голово_всеядных: 12
      логово_плотоядных: 12
      жилище_детенышей: 12  # 4шт до 12
      центр_альянса: 12

  13:
    buildings:
      улей: 13  # 1шт до 13
      ферма_яблок: 13  # 1шт до 13
      склад_песка: 10
      склад_листьев: 10
      склад_грунта: 10
      склад_яблок: 10
      флора_эволюции: 10
      голово_всеядных: 13
      логово_плотоядных: 13
      жилище_детенышей: 13  # 4шт до 13
      центр_альянса: 13
      центр_сбора_2: 1  # поставить центр сбора II
      склад_2: 1  # поставить склад II
    research:
      похвала_за_смелость: 1
      мутация_травоядных_1: 1
      мутация_плотоядных_1: 1
      мутация_всеядных_1: 1
      сверх_грабеж: 5
      начальная_атака: 3
      начальная_защита: 3

  14:
    buildings:
      улей: 14  # 1шт до 14
      ферма_яблок: 14  # 1шт до 14
      логово_плотоядных: 14
      жилище_детенышей: 14  # 5шт до 14 (добавляется еще одно)
      центр_альянса: 14
      склад_2_песка: 2
      склад_2_листьев: 2
      склад_2_грунта: 2
      склад_2_яблок: 2
    research:
      средняя_атака: 2
      средняя_защита: 2
      навык_уклонения: 5
      продвинутая_атака: 5
      продвинутая_защита: 3
      мутация_травоядных_2: 1
      мутация_плотоядных_2: 1
      мутация_всеядных_2: 1
      увеличение_опыта: 3

  15:
    buildings:
      ферма_яблок: 15  # 1шт до 15
      логово_плотоядных: 15
      жилище_детенышей: 15  # 5шт до 15
      центр_альянса: 15
      склад_2_песка: 3
      склад_2_листьев: 3
      склад_2_грунта: 3
      склад_2_яблок: 3
    research:
      преимущество_скорости: 5
      особый_отряд: 1
      эффективный_сбор: 5
      увеличение_грузоподъемности: 5

  16:
    buildings:
      ферма_яблок: 16  # 1шт до 16
      логово_плотоядных: 16
      жилище_детенышей: 16  # 5шт до 16
      склад_2_песка: 4
      склад_2_листьев: 4
      склад_2_грунта: 4
      склад_2_яблок: 4
    research:
      походный_отряд_1: 1
      походный_отряд_2: 1

  17:
    buildings:
      ферма_яблок: 17  # 1шт до 17
      жилище_детенышей: 17  # 5шт до 17
      склад_2_песка: 5
      склад_2_листьев: 5
      склад_2_грунта: 5
      склад_2_яблок: 5
    research:
      походный_отряд_3: 1
      развитие_района: 1
      доп_награды: 10
      средние_награды: 1
      эволюция_плотоядных: 1
      клыки_и_когти_1: 5

  18:
    buildings:
      центр_сбора_3: 1  # поставить центр сбора III
      склад_2_песка: 7
      склад_2_листьев: 7
      склад_2_грунта: 7
      склад_2_яблок: 6

  19:
    buildings:
      # Полная прокачка для поддержания
      все_здания_макс: 1
    research:
      все_исследования_макс: 1

# Настройки ускорения зданий (заполняется пользователем)
speedup_settings:
  # Основные здания
  улей: false
  ферма_грунта: true
  ферма_яблок: true
  ферма_листьев: false
  пруд: false

  # Эволюция и склады
  флора_эволюции: true
  склад_песка: false
  склад_листьев: false
  склад_грунта: false
  склад_яблок: false
  склад_воды: false

  # Боевые здания
  голово_всеядных: true
  логово_плотоядных: true
  жилище_детенышей: true

  # Альянс и центры
  центр_альянса: true
  центр_сбора_2: true
  центр_сбора_3: true
  склад_2: true

# Настройки ускорения исследований
research_speedup_settings:
  # Основные исследования
  развитие_территории: true
  изобилие_света: false
  сапротрофное_удобрение: false
  выхлый_грунт: false
  плодородная_почва: false

  # Производство
  журчащий_источник: false
  массивный_песчаник: false
  гигантский_улей: true
  загруженный_сборщик: false

  # Скорость
  резвый_подъем: true
  мягкая_почва: true
  скоростная_перевозка: true
  меткая_резка: true

  # Боевые исследования
  начальная_атака: true
  начальная_защита: true
  средняя_атака: true
  средняя_защита: true
  продвинутая_атака: true
  продвинутая_защита: true

  # Мутации
  мутация_травоядных_1: true
  мутация_плотоядных_1: true
  мутация_всеядных_1: true
  мутация_травоядных_2: true
  мутация_плотоядных_2: true
  мутация_всеядных_2: true

  # Походные отряды
  походный_отряд_1: true
  походный_отряд_2: true
  походный_отряд_3: true

# Минимальные интервалы проверки по уровню лорда (секунды)
min_check_intervals:
  lord_10_12: 300    # 5 минут - быстрые здания 30сек-5мин
  lord_13_15: 1800   # 30 минут - средние здания 30мин-2часа
  lord_16_18: 3600   # 1 час - долгие здания 4-8 часов
  lord_19_plus: 14400 # 4 часа - только фарм

# Настройки приоритетов действий
action_priorities:
  lord_upgrade_ready: 1000      # Готов к повышению лорда
  completed_buildings: 500      # Завершенные постройки
  quick_buildings_available: 200 # Быстрые здания доступны
  prime_time_bonus: 100         # Бонус за прайм-тайм
  per_hour_waiting: 1           # За каждый час ожидания

# Категории зданий для быстрого поиска
building_categories:
  farms:
    - ферма_грунта
    - ферма_яблок
    - ферма_листьев
    - улей
    - пруд

  storage:
    - склад_песка
    - склад_листьев
    - склад_грунта
    - склад_яблок
    - склад_воды
    - склад_2

  military:
    - голово_всеядных
    - логово_плотоядных
    - жилище_детенышей

  special:
    - флора_эволюции
    - центр_альянса
    - центр_сбора_2
    - центр_сбора_3

# Исследования по категориям
research_categories:
  economy:
    - развитие_территории
    - изобилие_света
    - сапротрофное_удобрение
    - выхлый_грунт
    - плодородная_почва
    - журчащий_источник
    - массивный_песчаник

  production:
    - гигантский_улей
    - загруженный_сборщик
    - резвый_подъем
    - мягкая_почва
    - скоростная_перевозка
    - накопитель

  combat:
    - меткая_резка
    - начальная_атака
    - начальная_защита
    - средняя_атака
    - средняя_защита
    - продвинутая_атака
    - продвинутая_защита

  mutations:
    - мутация_травоядных_1
    - мутация_плотоядных_1
    - мутация_всеядных_1
    - мутация_травоядных_2
    - мутация_плотоядных_2
    - мутация_всеядных_2

  special:
    - похвала_за_смелость
    - сверх_грабеж
    - особый_отряд
    - походный_отряд_1
    - походный_отряд_2
    - походный_отряд_3