# ИСПРАВЛЕННЫЕ требования для Beast Lord The New Land
# Логика: lord_requirements[X] = требования для повышения С (X-1) ДО X
# Например: lord_requirements[11] = что нужно чтобы повыситься с лорда 10 до лорда 11

# Требования по уровням лорда (ТОЛЬКО ЗДАНИЯ) - согласно "Список зданий.txt"
lord_requirements:
  11:  # Требования для повышения С 10 ДО 11 (между "Лорд 10" и "лорд 11")
    buildings:
      улей: 10        # 4шт до 10
      ферма_грунта: 10    # 4шт до 10
      ферма_яблок: 10     # 4шт до 10
      ферма_листьев: 10   # 4шт до 10
      пруд: 8             # 4шт до 8
      флора_эволюции: 7
      склад_песка: 7
      склад_листьев: 7
      склад_грунта: 7
      склад_яблок: 7
      склад_воды: 7
      голово_всеядных: 10
      логово_плотоядных: 10

  12:  # Требования для повышения С 11 ДО 12 (между "лорд 11" и "лорд 12")
    buildings:
      склад_песка: 8
      склад_листьев: 8
      склад_грунта: 8
      склад_яблок: 8
      флора_эволюции: 8
      улей: 11            # 1шт до 11
      ферма_грунта: 11    # 1шт до 11
      ферма_яблок: 11     # 1шт до 11
      голово_всеядных: 11
      логово_плотоядных: 11
      жилище_детенышей: 11    # 4шт до 11
      центр_альянса: 11

  13:  # Требования для повышения С 12 ДО 13 (между "лорд 12" и "лорд 13")
    buildings:
      склад_песка: 9
      склад_листьев: 9
      склад_грунта: 9
      склад_яблок: 9
      флора_эволюции: 9
      улей: 12            # 1шт до 12
      ферма_грунта: 12    # 1шт до 12
      ферма_яблок: 12     # 1шт до 12
      голово_всеядных: 12
      логово_плотоядных: 12
      жилище_детенышей: 12    # 4шт до 12
      центр_альянса: 12

  14:  # Требования для повышения С 13 ДО 14 (между "лорд 13" и "лорд 14")
    buildings:
      склад_песка: 10
      склад_листьев: 10
      склад_грунта: 10
      склад_яблок: 10
      флора_эволюции: 10
      улей: 13            # 1шт до 13
      ферма_яблок: 13     # 1шт до 13
      голово_всеядных: 13
      логово_плотоядных: 13
      жилище_детенышей: 13    # 4шт до 13
      центр_альянса: 13

  15:  # Требования для повышения С 14 ДО 15 (между "лорд 14" и "лорд 15")
    buildings:
      склад_песка_2: 2    # склад песка l: 2
      склад_листьев_2: 2  # склад листьев l: 2
      склад_грунта_2: 2   # склад грунта l: 2
      склад_яблок_2: 2    # склад яблок l: 2
      улей: 14            # 1шт до 14
      ферма_яблок: 14     # 1шт до 14
      логово_плотоядных: 14
      жилище_детенышей: 14    # 5шт до 14 (добавляется еще одно)
      центр_альянса: 14

  16:  # Требования для повышения С 15 ДО 16 (между "лорд 15" и "лорд 16")
    buildings:
      склад_песка_2: 3
      склад_листьев_2: 3
      склад_грунта_2: 3
      склад_яблок_2: 3
      ферма_яблок: 15     # 1шт до 15
      логово_плотоядных: 15
      жилище_детенышей: 15    # 5шт до 15
      центр_альянса: 15

  17:  # Требования для повышения С 16 ДО 17 (между "лорд 16" и "лорд 17")
    buildings:
      склад_песка_2: 4
      склад_листьев_2: 4
      склад_грунта_2: 4
      склад_яблок_2: 4
      ферма_яблок: 16     # 1шт до 16
      логово_плотоядных: 16
      жилище_детенышей: 16    # 5шт до 16

  18:  # Требования для повышения С 17 ДО 18 (между "лорд 17" и "лорд 18")
    buildings:
      склад_песка_2: 5
      склад_листьев_2: 5
      склад_грунта_2: 5
      склад_яблок_2: 5
      ферма_яблок: 17     # 1шт до 17
      жилище_детенышей: 17    # 5шт до 17

  19:  # Требования для повышения С 18 ДО 19 (между "лорд 18" и "дальше ничего строить не нужно")
    buildings:
      склад_песка_2: 7
      склад_листьев_2: 7
      склад_грунта_2: 7
      склад_яблок_2: 6

# ИСПРАВЛЕННЫЕ ветки исследований согласно "Исследования.txt"
# МЕХАНИКА: отдельная очередь исследований (1 слот)
research_branches:
  territory_development:
    min_lord_level: 10
    description: "Развитие территории (доступно с лорда 10)"
    researches:
      развитие_территории: 1    # Ветка исследований
      изобилие_света: 5
      сапротрофное_удобрение: 5
      выхлый_грунт: 5
      плодородная_почва: 5
      журчащий_источник: 5
      массивный_песчаник: 5
      гигантский_улей: 10
      загруженный_сборщик: 5
      резвый_подъем: 10
      мягкая_почва: 10
      скоростная_перевозка: 10
      меткая_резка: 1
      накопитель: 10

  basic_combat:
    min_lord_level: 13
    description: "Базовый бой (доступен с лорда 13)"
    researches:
      похвала_за_смелость: 1
      мутация_травоядных_1: 1
      мутация_плотоядных_1: 1
      мутация_всеядных_1: 1
      сверх_грабеж: 5
      начальная_атака: 3
      начальная_защита: 3
      мутация_травоядных_2: 1
      мутация_плотоядных_2: 1
      мутация_всеядных_2: 1
      увеличение_опыта: 3
      средняя_атака: 2
      средняя_защита: 2
      навык_уклонения: 5
      продвинутая_атака: 5
      продвинутая_защита: 3

  medium_combat:
    min_lord_level: 14
    description: "Средний бой (доступен с лорда 14)"
    researches:
      преимущество_скорости: 5

  special_squad:
    min_lord_level: 14
    description: "Особый отряд (доступен с лорда 14)"
    researches:
      начальный_совместный_бой: 1
      эффективный_сбор: 5
      увеличение_грузоподъемности: 5

  march_squads_1:
    min_lord_level: 17
    description: "Походный отряд I (доступен с лорда 17)"
    researches:
      эффективный_сбор: 5
      увеличение_грузоподъемности: 5

  march_squads_2:
    min_lord_level: 17
    description: "Походный отряд II (доступен с лорда 17)"
    researches:
      начальный_совместный_бой: 1
      эффективный_сбор: 5
      увеличение_грузоподъемности: 5

  district_development:
    min_lord_level: 17
    description: "Развитие района (доступно с лорда 17)"
    researches:
      эффективный_сбор: 10
      доп_награды: 10
      средние_награды: 1
      эволюция_плотоядных: 1
      клыки_и_когти_1: 5

  march_squads_3:
    min_lord_level: 17
    description: "Походный отряд III (доступен с лорда 17)"
    researches:
      начальный_совместный_бой: 1
      эффективный_сбор: 5
      увеличение_грузоподъемности: 5

# Настройки ускорения зданий (согласно txt файлам)
speedup_settings:
  # Основные здания
  улей: false
  ферма_грунта: true
  ферма_яблок: true
  ферма_листьев: false
  пруд: false

  # Эволюция и склады первого типа
  флора_эволюции: true
  склад_песка: false
  склад_листьев: false
  склад_грунта: false
  склад_яблок: false
  склад_воды: false

  # Боевые здания
  голово_всеядных: true
  логово_плотоядных: true
  жилище_детенышей: true

  # Альянс и центры
  центр_альянса: true

  # Склады второго типа
  склад_песка_2: false
  склад_листьев_2: false
  склад_грунта_2: false
  склад_яблок_2: false

# Настройки ускорения исследований
research_speedup_settings:
  # Развитие территории
  развитие_территории: true
  изобилие_света: false
  сапротрофное_удобрение: false
  выхлый_грунт: false
  плодородная_почва: false
  журчащий_источник: false
  массивный_песчаник: false
  гигантский_улей: true
  загруженный_сборщик: false
  резвый_подъем: true
  мягкая_почва: true
  скоростная_перевозка: true
  меткая_резка: true
  накопитель: true

  # Боевые исследования
  похвала_за_смелость: true
  мутация_травоядных_1: true
  мутация_плотоядных_1: true
  мутация_всеядных_1: true
  сверх_грабеж: false
  начальная_атака: true
  начальная_защита: true
  мутация_травоядных_2: true
  мутация_плотоядных_2: true
  мутация_всеядных_2: true
  увеличение_опыта: false
  средняя_атака: true
  средняя_защита: true
  навык_уклонения: false
  продвинутая_атака: true
  продвинутая_защита: true

  # Средний бой и особый отряд
  преимущество_скорости: true
  начальный_совместный_бой: true
  эффективный_сбор: false
  увеличение_грузоподъемности: false

  # Походные отряды и развитие района
  доп_награды: false
  средние_награды: true
  эволюция_плотоядных: true
  клыки_и_когти_1: false

# Остальные настройки
min_check_intervals:
  lord_10_12: 300    # 5 минут
  lord_13_15: 1800   # 30 минут
  lord_16_18: 3600   # 1 час
  lord_19_plus: 14400 # 4 часа

# Слоты для работы по готовности (механика игры)
game_slots:
  builder_slots_by_lord_level:    # Строители (зависят от уровня лорда)
    lord_10_15: 3                 # 3 строителя для лордов 10-15
    lord_16_plus: 4               # 4 строителя для лордов 16+
  research_slots: 1               # Исследования (отдельная очередь)
  training_slots: 1               # Тренировка войск

action_priorities:
  lord_upgrade_ready: 1000
  completed_buildings: 500
  completed_research: 500         # Добавлено для исследований
  free_builder_slot: 200          # Свободный слот строителя
  free_research_slot: 200         # Свободный слот исследований
  prime_time_bonus: 100
  per_hour_waiting: 1