# Требования для повышения лорда Beast Lord The New Land
# ТОЛЬКО ЗДАНИЯ блокируют повышение лорда
# Исследования качаются по готовности с ограничениями по веткам

# Требования по уровням лорда (ТОЛЬКО ЗДАНИЯ) - согласно txt файлам
lord_requirements:
  10:
    buildings:
      улей: 10  # 4шт до 10
      ферма_грунта: 10  # 4шт до 10
      ферма_яблок: 10  # 4шт до 10
      ферма_листьев: 10  # 4шт до 10
      пруд: 8  # 4шт до 8
      флора_эволюции: 7
      склад_песка: 7
      склад_листьев: 7
      склад_грунта: 7
      склад_яблок: 7
      склад_воды: 7
      голово_всеядных: 10
      логово_плотоядных: 10

  11:
    buildings:
      улей: 11  # 1шт до 11
      ферма_грунта: 11  # 1шт до 11
      ферма_яблок: 11  # 1шт до 11
      ферма_листьев: 10  # остается на 10
      пруд: 8  # остается на 8
      флора_эволюции: 8
      склад_песка: 8
      склад_листьев: 8
      склад_грунта: 8
      склад_яблок: 8
      склад_воды: 7  # остается на 7
      голово_всеядных: 11
      логово_плотоядных: 11
      жилище_детенышей: 11  # 4шт до 11
      центр_альянса: 11

  12:
    buildings:
      улей: 12  # 1шт до 12
      ферма_грунта: 12  # 1шт до 12
      ферма_яблок: 12  # 1шт до 12
      флора_эволюции: 9
      склад_песка: 9
      склад_листьев: 9
      склад_грунта: 9
      склад_яблок: 9
      голово_всеядных: 12
      логово_плотоядных: 12
      жилище_детенышей: 12  # 4шт до 12
      центр_альянса: 12

  13:
    buildings:
      улей: 13  # 1шт до 13
      ферма_яблок: 13  # 1шт до 13
      флора_эволюции: 10
      склад_песка: 10
      склад_листьев: 10
      склад_грунта: 10
      склад_яблок: 10
      голово_всеядных: 13
      логово_плотоядных: 13
      жилище_детенышей: 13  # 4шт до 13
      центр_альянса: 13
      центр_сбора_2: 1  # поставить центр сбора II
      склад_2: 1  # поставить склад II

  14:
    buildings:
      улей: 14  # 1шт до 14
      ферма_яблок: 14  # 1шт до 14
      логово_плотоядных: 14
      жилище_детенышей: 14  # 5шт до 14 (добавляется еще одно)
      центр_альянса: 14
      склад_2_песка: 2  # склад песка l: 2
      склад_2_листьев: 2  # склад листьев l: 2
      склад_2_грунта: 2  # склад грунта l: 2
      склад_2_яблок: 2  # склад яблок l: 2

  15:
    buildings:
      ферма_яблок: 15  # 1шт до 15
      логово_плотоядных: 15
      жилище_детенышей: 15  # 5шт до 15
      центр_альянса: 15
      склад_2_песка: 3
      склад_2_листьев: 3
      склад_2_грунта: 3
      склад_2_яблок: 3

  16:
    buildings:
      ферма_яблок: 16  # 1шт до 16
      логово_плотоядных: 16
      жилище_детенышей: 16  # 5шт до 16
      склад_2_песка: 4
      склад_2_листьев: 4
      склад_2_грунта: 4
      склад_2_яблок: 4

  17:
    buildings:
      ферма_яблок: 17  # 1шт до 17
      жилище_детенышей: 17  # 5шт до 17
      склад_2_песка: 5
      склад_2_листьев: 5
      склад_2_грунта: 5
      склад_2_яблок: 5

  18:
    buildings:
      центр_сбора_3: 1  # поставить центр сбора III
      склад_2_песка: 7
      склад_2_листьев: 7
      склад_2_грунта: 7
      склад_2_яблок: 6

  19:
    buildings:
      # Полная прокачка для поддержания
      все_здания_макс: 1

# ВЕТКИ ИССЛЕДОВАНИЙ согласно txt файлам (исправлено)
research_branches:
  territory_development:
    min_lord_level: 10
    description: "Развитие территории (доступно с лорда 10)"
    researches:
      развитие_территории: 1
      изобилие_света: 5
      сапротрофное_удобрение: 5
      выхлый_грунт: 5
      плодородная_почва: 5
      журчащий_источник: 5
      массивный_песчаник: 5
      гигантский_улей: 10
      загруженный_сборщик: 5
      резвый_подъем: 10
      мягкая_почва: 10
      скоростная_перевозка: 10
      меткая_резка: 1
      накопитель: 10

  basic_combat:
    min_lord_level: 13
    description: "Базовый бой (доступен с лорда 13)"
    researches:
      похвала_за_смелость: 1
      мутация_травоядных_1: 1
      мутация_плотоядных_1: 1
      мутация_всеядных_1: 1
      сверх_грабеж: 5
      начальная_атака: 3
      начальная_защита: 3
      мутация_травоядных_2: 1
      мутация_плотоядных_2: 1
      мутация_всеядных_2: 1
      увеличение_опыта: 3
      средняя_атака: 2
      средняя_защита: 2
      навык_уклонения: 5
      продвинутая_атака: 5
      продвинутая_защита: 3

  medium_combat:
    min_lord_level: 14
    description: "Средний бой (доступен с лорда 14)"
    researches:
      преимущество_скорости: 5
      особый_отряд: 1
      эффективный_сбор: 5
      увеличение_грузоподъемности: 5

  march_squads:
    min_lord_level: 17
    description: "Походные отряды (доступны с лорда 17)"
    researches:
      походный_отряд_1: 1
      походный_отряд_2: 1
      походный_отряд_3: 1
      развитие_района: 1
      доп_награды: 10
      средние_награды: 1
      эволюция_плотоядных: 1
      клыки_и_когти_1: 5

# Настройки ускорения зданий (обновлено согласно txt файлам)
speedup_settings:
  # Основные здания (качаются на разных этапах)
  улей: false  # качается до лорда 17
  ферма_грунта: true  # качается только до лорда 12
  ферма_яблок: true  # качается до лорда 17
  ферма_листьев: false  # качается только до лорда 10
  пруд: false  # качается только до лорда 10

  # Эволюция и склады первого типа
  флора_эволюции: true  # качается до лорда 13
  склад_песка: false  # качается до лорда 13
  склад_листьев: false  # качается до лорда 13
  склад_грунта: false  # качается до лорда 13
  склад_яблок: false  # качается до лорда 13
  склад_воды: false  # качается только до лорда 10

  # Боевые здания
  голово_всеядных: true  # качается до лорда 13
  логово_плотоядных: true  # качается до лорда 16
  жилище_детенышей: true  # качается до лорда 17

  # Альянс и центры
  центр_альянса: true  # качается до лорда 15
  центр_сбора_2: true  # строится на лорде 13
  центр_сбора_3: true  # строится на лорде 18
  склад_2: true  # строится на лорде 13

  # Склады второго типа (появляются с лорда 14)
  склад_2_песка: false  # качается с лорда 14 до 18
  склад_2_листьев: false  # качается с лорда 14 до 18
  склад_2_грунта: false  # качается с лорда 14 до 18
  склад_2_яблок: false  # качается с лорда 14 до 18

# Настройки ускорения исследований
research_speedup_settings:
  # Основные исследования
  развитие_территории: true
  изобилие_света: false
  сапротрофное_удобрение: false
  выхлый_грунт: false
  плодородная_почва: false

  # Производство
  журчащий_источник: false
  массивный_песчаник: false
  гигантский_улей: true
  загруженный_сборщик: false

  # Скорость
  резвый_подъем: true
  мягкая_почва: true
  скоростная_перевозка: true
  меткая_резка: true

  # Боевые исследования
  начальная_атака: true
  начальная_защита: true
  средняя_атака: true
  средняя_защита: true
  продвинутая_атака: true
  продвинутая_защита: true

  # Мутации
  мутация_травоядных_1: true
  мутация_плотоядных_1: true
  мутация_всеядных_1: true
  мутация_травоядных_2: true
  мутация_плотоядных_2: true
  мутация_всеядных_2: true

  # Походные отряды
  походный_отряд_1: true
  походный_отряд_2: true
  походный_отряд_3: true

# Остальные настройки остаются без изменений...
min_check_intervals:
  lord_10_12: 300    # 5 минут
  lord_13_15: 1800   # 30 минут
  lord_16_18: 3600   # 1 час
  lord_19_plus: 14400 # 4 часа

action_priorities:
  lord_upgrade_ready: 1000
  completed_buildings: 500
  quick_buildings_available: 200
  prime_time_bonus: 100
  per_hour_waiting: 1