# Детальная конфигурация прайм-таймов для Beast Lord The New Land
# Основано на файле "Prime Time_fixed_v3.txt"

prime_times:
  # ПОНЕДЕЛЬНИК - РАЗВИТИЕ МУРАВЕЙНИКА
  понедельник:
    "03:05": "сила зданий"
    "04:05": "сила эволюции, ускор на эволюцию"
    "05:05": "сила зданий"
    "06:05": "ускорение"
    "07:05": "сила эволюции, сила зданий"
    "08:05": "сила зданий, ускор на постройку"
    "09:05": "сила зданий, сила эволюции, вылуп солдат"
    "10:05": "сила зданий, сила эволюции, вылуп солдат"
    "11:05": "сила зданий"
    "12:05": "сила эволюции, ускор на эволюцию"
    "13:05": "сила зданий"
    "14:05": "ускорение"
    "15:05": "сила эволюции, сила зданий"
    "16:05": "сила зданий, ускор на постройку"
    "17:05": "сила зданий, сила эволюции, вылуп солдат"
    "18:05": "сила зданий, сила эволюции, вылуп солдат"
    "19:05": "сила зданий"
    "20:05": "сила эволюции, ускор на эволюцию"
    "21:05": "сила зданий"
    "22:05": "ускорение"
    "23:05": "сила эволюции, сила зданий"
    "00:05": "сила зданий, ускор на постройку"
    "01:05": "сила зданий, сила эволюции, вылуп солдат"
    "02:05": "сила зданий, сила эволюции, вылуп солдат ⭐"

  # ВТОРНИК - СБОР РЕСУРСОВ
  вторник:
    "03:05": "сила зданий, ускор на постройку"
    "04:05": "сила зданий, клетки, эссенция жизни"
    "05:05": "ускорение на вылуплении"
    "06:05": "сила зданий ⭐, вылупление солдат, клетки"
    "07:05": "ускор на постройку, ускор на вылупление, ускор на эволюцию"
    "08:05": "сила зданий, сила эволюции, ускор на вылупление"
    "09:05": "сила эволюции ⭐, сила зданий, вылупление солдат"
    "10:05": "сила зданий, клетки, эссенция жизни"
    "11:05": "сила зданий, ускор на постройку"
    "12:05": "сила зданий, клетки, эссенция жизни"
    "13:05": "ускорение на вылуплении"
    "14:05": "сила зданий ⭐, вылупление солдат, клетки"
    "15:05": "ускор на постройку, ускор на вылупление, ускор на эволюцию"
    "16:05": "сила зданий, сила эволюции, ускор на вылупление"
    "17:05": "сила эволюции ⭐, сила зданий, вылупление солдат"
    "18:05": "сила зданий, клетки, эссенция жизни"
    "19:05": "сила зданий, ускор на постройку"
    "20:05": "сила зданий, клетки, эссенция жизни"
    "21:05": "ускорение на вылуплении"
    "22:05": "сила зданий ⭐, вылупление солдат, клетки"
    "23:05": "ускор на постройку, ускор на вылупление, ускор на эволюцию"
    "00:05": "сила зданий, сила эволюции, ускор на вылупление"
    "01:05": "сила эволюции, сила зданий ⭐, вылупление солдат"
    "02:05": "сила зданий, клетки, эссенция жизни"

  # СРЕДА - ЭВОЛЮЦИЯ
  среда:
    "03:05": "сила зданий, ускор на постройку"
    "04:05": "сила эволюции, ускор на эволюцию, останки животных"
    "05:05": "ускорение на вылуплении"
    "06:05": "сила эволюции, сила зданий, останки животных"
    "07:05": "сила зданий, вылупление солдат"
    "08:05": "ускор на постройку, ускор на вылупление, ускор на эволюцию, останки животных"
    "09:05": "сила зданий, сила эволюции, вылупление солдат"
    "10:05": "ускор на постройку, ускор на выпущении, ускор на эволюцию, останки животных"
    "11:05": "сила зданий, ускор на постройку"
    "12:05": "сила эволюции 💖, ускор на эволюцию, останки животных"
    "13:05": "ускорение на вылуплении"
    "14:05": "сила эволюции, сила зданий, останки животных"
    "15:05": "сила зданий, вылупление солдат"
    "16:05": "ускор на постройку, ускор на выпущении, ускор на эволюцию, останки животных"
    "17:05": "сила зданий, сила эволюции, вылупление солдат"
    "18:05": "ускор на постройку, ускор на выпущении, ускор на эволюцию, останки животных"
    "19:05": "сила зданий, ускор на постройку"
    "20:05": "сила эволюции 💖, ускор на эволюцию, останки животных"
    "21:05": "ускор на выпущении"
    "22:05": "сила эволюции, сила зданий, останки животных"
    "23:05": "сила зданий, вылупление солдат"
    "00:05": "ускор на постройку, ускор на выпущении, ускор на эволюцию, останки животных"
    "01:05": "сила зданий, сила эволюции, ускор на вылупление"
    "02:05": "ускор на постройку, ускор на выпущении, ускор на эволюцию, останки животных"

  # ЧЕТВЕРГ - СПЕЦУСЛУГИ
  четверг:
    "03:05": "сила зданий, ускор на постройку"
    "04:05": "мут споры, яйца 💖, опыт, навыки"
    "05:05": "ускор на постройку, ускор на вылупление, ускор на эволюцию"
    "06:05": "мут споры, яйца 💖, опыт, навыки"
    "07:05": "ускорение"
    "08:05": "мут споры, яйца 💖, опыт, навыки"
    "09:05": "сила эволюции, сила зданий, ускор на вылупление"
    "10:05": "мут споры, яйца 💖, опыт, навыки"
    "11:05": "сила зданий, ускор на постройку"
    "12:05": "мут споры, яйца 💖, опыт, навыки"
    "13:05": "ускор на постройку, ускор на вылупление, ускор на эволюцию"
    "14:05": "мут споры, яйца 💖, опыт, навыки"
    "15:05": "ускорение"
    "16:05": "мут споры, яйца 💖, опыт, навыки"
    "17:05": "сила эволюции, вылуп солдат, ускор на вылупление"
    "18:05": "мут споры, яйца 💖, опыт, навыки"
    "19:05": "сила зданий, ускор на постройку"
    "20:05": "мут споры, яйца 💖, опыт, навыки"
    "21:05": "ускор на постройку, ускор на вылупление, ускор на эволюцию"
    "22:05": "мут споры, яйца 💖, опыт, навыки"
    "23:05": "ускорение"
    "00:05": "мут споры, яйца 💖, опыт, навыки"
    "01:05": "сила эволюции, сила зданий, ускор на вылупление"
    "02:05": "мут споры, яйца 💖, опыт, навыки"

  # ПЯТНИЦА - ВЫПУЩЕННЫЕ СОЛДАТ
  пятница:
    "03:05": "ускорение"
    "04:05": "ускор на постройку, ускор на вылупление, ускор на эволюцию"
    "05:05": "сила зданий, сила эволюции, ускор на вылупление"
    "06:05": "ускорение на вылуплении"
    "07:05": "сила зданий, сила эволюции, ускор на вылупление"
    "08:05": "сила зданий, вылупление солдат"
    "09:05": "сила эволюции, вылупление солдат"
    "10:05": "ускорение"
    "11:05": "ускорение"
    "12:05": "ускор на постройку, ускор на вылупление, ускор на эволюцию"
    "13:05": "сила зданий, сила эволюции, ускор на вылупление"
    "14:05": "ускорение на вылуплении"
    "15:05": "сила зданий, сила эволюции, ускор на вылупление"
    "16:05": "сила зданий, вылупление солдат"
    "17:05": "сила зданий ⭐, вылупление солдат"
    "18:05": "ускорение"
    "19:05": "ускорение"
    "20:05": "ускор на постройку, ускор на вылупление, ускор на эволюцию"
    "21:05": "сила зданий, сила эволюции, ускор на вылупление"
    "22:05": "ускорение на вылуплении"
    "23:05": "сила зданий, сила эволюции, ускор на вылупление"
    "00:05": "сила зданий, вылупление солдат"
    "01:05": "сила зданий ⭐, вылупление солдат"
    "02:05": "ускорение"

  # СУББОТА - НА ВЫБОР (ЛУЧШЕ СБОР)
  суббота:
    "03:05": "ускорение"
    "04:05": "сила эволюции, ускор на эволюцию"
    "05:05": "сила зданий, ускор на постройку"
    "06:05": "ускорение на вылуплении"
    "07:05": "сила эволюции, сила зданий, ускор на вылупление"
    "08:05": "сила эволюции, сила зданий, ускор на вылупление"
    "09:05": "сила зданий ⭐, вылупление солдат"
    "10:05": "сила эволюции ⭐, вылупление солдат"
    "11:05": "ускорение"
    "12:05": "сила эволюции, ускор на эволюцию"
    "13:05": "сила зданий, ускор на постройку"
    "14:05": "ускорение на вылуплении"
    "15:05": "сила эволюции, сила зданий, ускор на вылупление"
    "16:05": "сила эволюции, сила зданий, ускор на вылупление"
    "17:05": "сила зданий ⭐, вылупление солдат"
    "18:05": "сила эволюции ⭐, вылупление солдат"
    "19:05": "ускорение"
    "20:05": "сила эволюции, ускор на эволюцию"
    "21:05": "сила зданий, ускор на постройку"
    "22:05": "ускорение на вылуплении"
    "23:05": "сила эволюции, сила зданий, ускор на вылупление"
    "00:05": "сила эволюции, сила зданий, ускор на вылупление"
    "01:05": "сила зданий ⭐, вылупление солдат"
    "02:05": "сила эволюции ⭐, вылупление солдат"

  # ВОСКРЕСЕНЬЕ - СУММ/РАЙОН/СТОП
  воскресенье:
    "03:05": "сила зданий, ускор на постройку"
    "04:05": "ускорение вылуп/улучш дикого 💖, корм, скорлупа"
    "05:05": "ускор на постройку, ускор на вылупление, ускор на эволюцию"
    "06:05": "сила эволюции, ускорение вылуп/улучш дикого 💖, корм, скорлупа"
    "07:05": "ускорение"
    "08:05": "ускорение вылуп/улучш дикого 💖, корм, скорлупа"
    "09:05": "сила эволюции, сила зданий, ускор на вылупление"
    "10:05": "вылупленные дикой, корм, скорлупа"
    "11:05": "сила зданий, ускор на постройку"
    "12:05": "ускорение вылуп/улучш дикого 💖, корм, скорлупа"
    "13:05": "ускор на постройку, ускор на вылупление, ускор на эволюцию"
    "14:05": "сила эволюции, скорение вылуп/улучш дикого 💖, корм, скорлупа"
    "15:05": "ускорение"
    "16:05": "ускорение вылуп/улучш дикого 💖, корм, скорлупа"
    "17:05": "сила эволюции, сила зданий, ускор на вылупление"
    "18:05": "ускорение вылуп/улучш дикого 💖, корм, скорлупа"
    "19:05": "сила зданий, ускор на постройку"
    "20:05": "ускорение вылуп/улучш дикого 💖, корм, скорлупа"
    "21:05": "ускор на постройку, ускор на вылупление, ускор на эволюцию"
    "22:05": "сила эволюции 💖, вылупление солдат, корм, скорлупа"
    "23:05": "ускорение"
    "00:05": "сила эволюции, ускорение вылуп/улучш дикого 💖, корм, скорлупа"
    "01:05": "сила эволюции, сила зданий, ускор на вылупление"
    "02:05": "ускорение вылуп/улучш дикого 💖, корм, скорлупа"

# Настройки системы прайм-таймов
settings:
  # Максимальное время ожидания прайм-тайма (в часах)
  max_wait_hours: 2.0

  # Допуск по времени для определения активного прайм-тайма (в минутах)
  tolerance_minutes: 5

  # Интервал проверки прайм-таймов (в секундах)
  check_interval: 300

  # Бонусы приоритета для разных типов действий в прайм-тайм
  priority_bonuses:
    building_power: 200      # Сила зданий
    evolution_bonus: 150     # Сила эволюции
    training_bonus: 100      # Вылупление солдат
    resource_bonus: 100      # Клетки, эссенция
    special_services: 80     # Споры, яйца, опыт
    wild_bonus: 60          # Дикая природа
    speedup_bonus: 50       # Ускорения
    general_bonus: 40       # Общие бонусы