# Конфигурация TUI интерфейса Beast Lord Bot
# Версия 2.6 - Простой TUI интерфейс

tui:
  # Единственная основная настройка
  max_concurrent_emulators: 5     # Максимум одновременно обрабатываемых эмуляторов

  # Настройки отображения
  theme: "default"                # Тема интерфейса (пока только default)
  log_level: "INFO"               # Уровень логирования (DEBUG, INFO, WARNING, ERROR)
  auto_refresh_interval: 5        # Обновление статуса каждые N секунд

# Сохраненные пользовательские настройки
# Эта секция автоматически обновляется приложением
user_preferences:
  enabled_emulators: []           # ID включенных эмуляторов (обновляется автоматически)
  last_used_screen: "main"        # Последний использованный экран (обновляется автоматически)